package com.demo.upimesh.ui.navigation

sealed class Screen(val route: String, val title: String) {
    object Splash : Screen("splash", "Splash")
    object Login : Screen("login", "Login")
    object Register : Screen("register", "Register")
    object RegistrationSuccess : Screen("registration_success", "Registration Success")
    object ForgotPassword : Screen("forgot_password", "Forgot Password")
    object OtpVerification : Screen("otp_verification", "OTP Verification")
    object Home : Screen("home", "Home")
    object Contacts : Screen("contacts", "Contacts")
    object SendMoney : Screen("send_money", "Send Money")
    object ReceiveMoney : Screen("receive_money", "Receive Money")
    object QrScanner : Screen("qr_scanner", "QR Scanner")
    object QrGenerator : Screen("qr_generator", "QR Code")
    object OfflineQueue : Screen("offline_queue", "Offline Queue")
    object MeshStatus : Screen("mesh_status", "BLE Mesh Topology")
    object BluetoothTransfer : Screen("bluetooth_transfer", "Bluetooth Transfer")
    object TransactionTimeline : Screen("timeline", "Timeline")
    object Receipt : Screen("receipt", "Receipt")
    object SmsInbox : Screen("sms_inbox", "SMS Inbox")
    object Notifications : Screen("notifications", "Notifications")
    object TransactionHistory : Screen("history", "History")
    object Analytics : Screen("analytics", "Analytics")
    object Profile : Screen("profile", "Profile")
    object Settings : Screen("settings", "Settings")
    object PresentationMode : Screen("presentation_mode", "Presentation Supervisor")
    object DemoMode : Screen("demo_mode", "Automated Demo")
    object SecurityClassroom : Screen("security_classroom", "Security Classroom")
    object DeveloperMode : Screen("developer_mode", "Developer Console")
}
